version: '3.8'

services:

  php:
    build:
      context: ./docker/php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - database

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: cloudtasks_db2
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  mailer:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  db-data:
