name: CI Symfony CloudTasks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    workflow_dispatch:

jobs:
  symfony:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: cloudtasks_db
          POSTGRES_USER: app
          POSTGRES_PASSWORD: password
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: "pgsql://app:password@localhost:5432/cloudtasks_db"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: intl, pdo_pgsql
          coverage: none

      - name: Install Composer dependencies
        run: |
          cd app
          composer install --no-progress --no-interaction

      - name: Drop and Create Database
        run: |
          cd app
          php bin/console doctrine:database:drop --force || true
          php bin/console doctrine:database:create

      - name: Run Doctrine migrations
        run: |
          cd app
          php bin/console doctrine:migrations:migrate --no-interaction

      - name: Run PHPUnit tests
        run: |
          cd app
          php bin/phpunit

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cloudtasks-app ./app

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/cloudtasks-app
